### ISSUE TITLE
Refactor Auth

### ISSUE THREAD

**Issue by Gloobywerts** [EDA-Gurgl/gurgl#146]
the issue appears to be with the sodium npm package

**Comment by BrenMurrell** [comment]
Hey @Gloobywerts, we've got @alisa17 looking at options for stripping out the auth stuff at the mo and replacing it with something a little more user friendly  / OS agnostic

**Comment by BrenMurrell** [comment]
resolved and merged into dev with PR 150 https://github.com/EDA-Gurgl/gurgl/pull/150
